/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import {
  ShieldAlert,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  Layers,
  Camera,
  Hash,
  BookOpen,
  Scale,
  Cpu,
} from 'lucide-react';

export const AboutScreen: React.FC = () => {
  return (
    <div className="space-y-8 max-w-4xl mx-auto pb-16">
      {/* 1. Header Banner */}
      <div className="bg-[#0B1528] border border-[#1E2E4A] rounded-2xl p-6 sm:p-8 text-white space-y-4 shadow-xl">
        <div className="flex items-center gap-2 text-xs font-mono text-cyan-400 uppercase tracking-wider">
          <BookOpen className="w-4 h-4 text-cyan-400" />
          <span>Standard Operating Procedure & Architectural Specification</span>
        </div>

        <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
          Digital Companion for Field Drug Testing
        </h1>

        <p className="text-sm text-slate-200 leading-relaxed max-w-3xl">
          An operational decision-support tool engineered for forensic field officers, law enforcement,
          and border security agencies. Designed for rapid, verifiable digital documentation of
          validated colorimetric chemical reagent kits.
        </p>
      </div>

      {/* 2. Critical Safety & Technical Limitation Statement (Requirement 10) */}
      <div className="bg-rose-950/40 border-2 border-rose-500/60 rounded-2xl p-6 text-white space-y-3 shadow-md">
        <div className="flex items-start gap-3">
          <ShieldAlert className="w-6 h-6 text-rose-400 shrink-0 mt-0.5" />
          <div className="space-y-2">
            <h2 className="text-base font-bold text-rose-300">
              Crucial Safety & Technical Boundary (Non-Negotiable)
            </h2>
            <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
              This application <strong className="text-rose-300">DOES NOT</strong> accept raw images of
              unknown powders, liquids, or plants to directly classify them as illicit narcotics.
              Direct visual inspection of an unreacted substance cannot provide chemical specificity.
            </p>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
              The Digital Companion functions strictly as a <em>secondary analytical reader</em> for
              <strong> certified chemical field-testing kits</strong> (e.g., Marquis, Scott, Duquenois-Levine).
              It captures the resulting chemical chromophore shift alongside a physical reference color card to eliminate subjective human error and lighting bias.
            </p>
            <div className="bg-slate-950/80 p-3 rounded-lg border border-rose-500/30 text-xs text-rose-200 font-mono">
              SCREENING NOTICE: All results generated by this tool are presumptive field screening outcomes. Confirmatory laboratory analysis (GC-MS / LC-MS / FTIR) remains required for judicial proceedings.
            </div>
          </div>
        </div>
      </div>

      {/* 3. Core System Architecture Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Module A: Dual-Zone Capture */}
        <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-lg bg-cyan-50 text-cyan-600 flex items-center justify-center">
            <Camera className="w-4 h-4" />
          </div>
          <h3 className="text-sm font-bold text-slate-900">
            1. Dual-Zone Optical Standardization
          </h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            Every inspection requires framing both the reacted chemical well/strip and the physical reference card in the same frame. This ensures both surfaces experience identical ambient lighting and camera white balance.
          </p>
        </div>

        {/* Module B: Lighting Compensation */}
        <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center">
            <Layers className="w-4 h-4" />
          </div>
          <h3 className="text-sm font-bold text-slate-900">
            2. Reference-Card Lighting Normalization
          </h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            Outdoor sunlight (5500K–6500K), sodium street lamps (2000K), and tungsten flashlights shift RGB values dramatically. By sampling the certified reference white patch, the algorithm calculates chromatic gain factors ($k_R, k_G, k_B$) to normalize colors to standard D65 illuminant.
          </p>
        </div>

        {/* Module C: Calibrated ML Classifier */}
        <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-lg bg-purple-50 text-purple-600 flex items-center justify-center">
            <Cpu className="w-4 h-4" />
          </div>
          <h3 className="text-sm font-bold text-slate-900">
            3. Machine-Learning Classification Module
          </h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            The decision engine maps compensated chromophore coordinates in CIELAB space and evaluates CIE94 Delta-E color distance against trained labeled datasets. Classifies reactions into POSITIVE, NEGATIVE, or INCONCLUSIVE with calculated confidence scores.
          </p>
        </div>

        {/* Module D: Tamper-Evident SHA-256 */}
        <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-3">
          <div className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center">
            <Hash className="w-4 h-4" />
          </div>
          <h3 className="text-sm font-bold text-slate-900">
            4. SHA-256 Cryptographic Tamper-Evidence
          </h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            At the millisecond of capture, the uncompressed image data is processed through the browser Web Crypto API to generate a unique 256-bit hexadecimal hash. Any unauthorized modification or pixel alteration produces an immediate hash mismatch.
          </p>
        </div>
      </div>

      {/* 4. Step-by-Step Field Officer SOP */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-4">
        <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
          <Scale className="w-4 h-4 text-slate-700" />
          <span>Standard Operating Procedure (SOP) for Field Personnel</span>
        </h2>

        <ol className="space-y-3 text-xs text-slate-700 list-decimal list-inside leading-relaxed">
          <li className="pl-1">
            <strong className="text-slate-900">Reagent Selection & Safety:</strong> Put on nitrile gloves and eye protection. Select the appropriate validated chemical kit (e.g. Marquis for suspected opioids, Scott for suspected cocaine).
          </li>
          <li className="pl-1">
            <strong className="text-slate-900">Chemical Reaction:</strong> Introduce a pinhead-sized sample (approx. 1–2 mg) into the reaction chamber. Allow reaction to develop for the specified incubation duration (typically 30–60 seconds).
          </li>
          <li className="pl-1">
            <strong className="text-slate-900">Dual-Target Camera Framing:</strong> Place the physical reference color card directly alongside the reacted kit. Open the camera interface and align both targets within the on-screen reticles.
          </li>
          <li className="pl-1">
            <strong className="text-slate-900">Optical Inspection & Compensation:</strong> The companion extracts raw RGB/HSV, applies lighting compensation, and computes Delta-E against the kit's baseline profile.
          </li>
          <li className="pl-1">
            <strong className="text-slate-900">Ledger Entry & Evidence Sealing:</strong> Review the classification outcome. The system automatically creates a timestamped, GPS-tagged digital record sealed with a SHA-256 cryptographic digest.
          </li>
        </ol>
      </div>

      {/* 5. Supported Validated Kits Table */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm space-y-4">
        <h2 className="text-base font-bold text-slate-900">
          Supported Validated Chemical Test Kits
        </h2>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 text-slate-400 font-mono text-[10px] uppercase">
                <th className="pb-2">Kit Name</th>
                <th className="pb-2">Target Analyte Class</th>
                <th className="pb-2">Expected Positive Chromophore</th>
                <th className="pb-2">Standard Rx Time</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-slate-700">
              <tr>
                <td className="py-2.5 font-semibold text-slate-900">Marquis Reagent</td>
                <td className="py-2.5">Opioids (Heroin, Morphine, Codeine)</td>
                <td className="py-2.5 font-mono text-purple-700 font-bold">Deep Violet-Purple</td>
                <td className="py-2.5 font-mono">30s</td>
              </tr>
              <tr>
                <td className="py-2.5 font-semibold text-slate-900">Scott Reagent Test</td>
                <td className="py-2.5">Cocaine Base & Cocaine HCl</td>
                <td className="py-2.5 font-mono text-blue-700 font-bold">Distinct Cobalt Blue</td>
                <td className="py-2.5 font-mono">45s</td>
              </tr>
              <tr>
                <td className="py-2.5 font-semibold text-slate-900">Duquenois-Levine</td>
                <td className="py-2.5">Cannabinoids (THC / Plant Resins)</td>
                <td className="py-2.5 font-mono text-indigo-700 font-bold">Deep Violet / Indigo</td>
                <td className="py-2.5 font-mono">60s</td>
              </tr>
              <tr>
                <td className="py-2.5 font-semibold text-slate-900">Lateral Flow Fentanyl Strip</td>
                <td className="py-2.5">Synthetic Fentanyl Analogues</td>
                <td className="py-2.5 font-mono text-rose-700 font-bold">Single Control Band</td>
                <td className="py-2.5 font-mono">120s</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
